StoredConfig =  {
settings = {
  dodebuff = false ,
  doheal = false ,
  dobuff = true,
  docure = false ,
  domelee = true,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = false ,
  dosit = true,
  doforage = false ,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = true,
  acleash = 40,
  followdistance = 20,
  zradius = 100,
  campRestDistance = 10,
  maCampAnchor = true,
},
pull = {
  spell = {
    gem = "melee",
    spell = "",
  },
  radius = 400,
  zrange = 150,
  pullMinCon = 2,
  pullMaxCon = 5,
  maxLevelDiff = 6,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR', 'DRU', 'SHM' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = false ,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  stayBehind = true,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = false ,
  minmana = 0,
  otoffset = 0,
},
heal = {
  rezoffset = 0,
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
  },
},
buff = {
  spells = {
    {
      gem = 6,
      spell = "Shrink",
      alias = "shrink",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
      precondition = "return (mq.TLO.Spawn(EvalID).Height() or 0) > 2.5",
    },
    {
      gem = 6,
      spell = "Enduring Breath",
      alias = "eb",
      minmana = 0,
      enabled = false ,
      inCombat = true,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'self', 'tank', 'pc', 'groupmember' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 8,
      spell = "Spirit of Sharik",
      alias = "pet",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'self' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = "item",
      spell = "Bestial Trousers",
      alias = "sta",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
  },
},
debuff = {
  spells = {
  },
},
cure = {
  spells = {
  },
},
script = {
},
}
return StoredConfig