StoredConfig =  {
settings = {
  dodebuff = true,
  doheal = true,
  dobuff = true,
  docure = false ,
  domelee = false ,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = "none",
  dosit = true,
  doforage = false ,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = true,
  acleash = 40,
  followdistance = 20,
  zradius = 100,
  campRestDistance = 10,
  maCampAnchor = true,
},
pull = {
  spell = {
    gem = "melee",
    spell = "",
  },
  radius = 400,
  zrange = 150,
  pullMinCon = 2,
  pullMaxCon = 5,
  maxLevelDiff = 6,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR', 'DRU', 'SHM' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = false ,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  stayBehind = false ,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = false ,
  minmana = 0,
  otoffset = 0,
},
heal = {
  rezoffset = 0,
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
    {
      gem = 1,
      spell = "Kragg's Salve",
      alias = "heal",
      enabled = true,
      bands = {
        {
          targetphase = { 'groupmember', 'pc', 'self', 'tank' },
          validtargets = { 'all' },
          min = 0,
          max = 70,
        },
      },
    },
  },
},
buff = {
  spells = {
    {
      gem = 6,
      spell = "Shrink",
      alias = "shrink",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      bands = {
        {
          targetphase = { 'groupmember', 'self', 'tank' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
      precondition = "return (mq.TLO.Spawn(EvalID).Height() or 0) > 2.4",
    },
    {
      gem = 8,
      spell = "Stamina",
      alias = false ,
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'tank', 'groupmember' },
          validtargets = { 'war', 'shd', 'pal', 'rng', 'mnk', 'rog', 'brd', 'bst', 'ber' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 8,
      spell = "Tumultuous Strength",
      alias = false ,
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'self', 'groupbuff' },
          validtargets = { 'war', 'shd', 'pal', 'rng', 'mnk', 'rog', 'brd', 'bst', 'ber' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 5,
      spell = "Chloroplast",
      alias = "regen",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 8,
      spell = "Alacrity",
      alias = false ,
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'tank', 'pet', 'groupmember', 'mypet' },
          validtargets = { 'war', 'shd', 'pal', 'rng', 'mnk', 'ber', 'bst', 'brd', 'rog' },
        },
      },
      spellicon = 0,
    },
  },
},
debuff = {
  spells = {
    {
      gem = 2,
      spell = "Turgur's Insects",
      alias = false ,
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 20,
          max = 95,
        },
      },
      recast = 0,
      delay = 0,
    },
    {
      gem = 3,
      spell = "Malosi",
      alias = "malo",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 20,
          max = 99,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Maloed' },
    },
    {
      gem = 4,
      spell = "Cripple",
      alias = "cripple",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 20,
          max = 99,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Crippled' },
    },
  },
},
cure = {
  spells = {
    {
      gem = 7,
      spell = "Cure Poison",
      alias = "curepois",
      minmana = 0,
      curetype = { 'poison' },
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember', 'pc' },
          validtargets = { 'all' },
        },
      },
    },
    {
      gem = 7,
      spell = "Cure Disease",
      alias = "curedis",
      minmana = 0,
      curetype = { 'disease' },
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember', 'pc' },
          validtargets = { 'all' },
        },
      },
    },
  },
},
script = {
},
}
return StoredConfig