StoredConfig =  {
settings = {
  dodebuff = true,
  doheal = false ,
  dobuff = true,
  docure = false ,
  domelee = false ,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = false ,
  dosit = true,
  doforage = false ,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = false ,
  acleash = 50,
  followdistance = 20,
  zradius = 150,
  campRestDistance = 10,
  maCampAnchor = true,
},
pull = {
  spell = {
    gem = "melee",
    spell = "",
  },
  radius = 400,
  zrange = 150,
  pullMinCon = 2,
  pullMaxCon = 5,
  maxLevelDiff = 6,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR', 'DRU', 'SHM' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = false ,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  stayBehind = false ,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = false ,
  minmana = 0,
  otoffset = 0,
},
heal = {
  rezoffset = 0,
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
  },
},
buff = {
  spells = {
    {
      gem = 8,
      spell = "Arch Shielding",
      alias = "selfshield",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'self' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 7,
      spell = "Strengthen",
      alias = "str",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'tank', 'groupmember' },
          validtargets = { 'war', 'shd', 'pal', 'rng', 'mnk', 'rog', 'brd', 'bst', 'ber' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 7,
      spell = "Aanya's Quickening",
      alias = "haste",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'tank', 'groupmember' },
          validtargets = { 'war', 'shd', 'pal', 'rng', 'mnk', 'ber', 'bst', 'brd', 'rog' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 7,
      spell = "Clarity",
      alias = "clarity",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'self', 'groupmember', 'pc' },
          validtargets = { 'pal', 'shd', 'rng', 'bst', 'shm', 'clr', 'dru', 'wiz', 'mag', 'enc', 'nec' },
        },
      },
      spellicon = 0,
    },
  },
},
debuff = {
  spells = {
    {
      gem = 3,
      spell = "Dazzle",
      alias = "mez",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'notmatar' },
          validtargets = {  },
          min = 50,
          max = 100,
          mintar = 1,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Mezzed' },
    },
    {
      gem = 1,
      spell = "Gasping Embrace",
      alias = "dot",
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 50,
          max = 99,
        },
      },
    },
    {
      gem = 2,
      spell = "Tashani",
      alias = "tash",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar', 'notmatar', 'named' },
          validtargets = {  },
          min = 20,
          max = 100,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Tashed' },
    },
    {
      gem = 4,
      spell = "Cripple",
      alias = "cripple",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 20,
          max = 99,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Crippled' },
    },
  },
},
cure = {
  spells = {
  },
},
script = {
},
}
return StoredConfig