StoredConfig =  {
settings = {
  dodebuff = false ,
  doheal = true,
  dobuff = true,
  docure = true,
  domelee = false ,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = false ,
  dosit = true,
  doforage = false ,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = false ,
  acleash = 40,
  followdistance = 20,
  zradius = 100,
  campRestDistance = 10,
  maCampAnchor = true,
},
pull = {
  spell = {
    gem = "melee",
    spell = "",
  },
  radius = 400,
  zrange = 150,
  pullMinCon = 2,
  pullMaxCon = 5,
  maxLevelDiff = 6,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR', 'DRU', 'SHM' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = false ,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  stayBehind = false ,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = false ,
  minmana = 0,
  otoffset = 0,
},
heal = {
  rezoffset = 0,
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
    {
      gem = 4,
      spell = "Word of Healing",
      alias = "grpheal",
      minmana = 0,
      minmanapct = 0,
      maxmanapct = 100,
      enabled = true,
      inCombat = false ,
      tarcnt = 2,
      bands = {
        {
          targetphase = { 'groupheal' },
          validtargets = { 'all' },
          min = 0,
          max = 70,
        },
      },
      healResource = "hp",
    },
    {
      gem = 1,
      spell = "Divine Light",
      alias = "heal",
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'groupmember', 'pc', 'tank' },
          validtargets = { 'all' },
          min = 1,
          max = 60,
        },
      },
    },
    {
      gem = 6,
      spell = "Restoration",
      alias = "rez",
      minmana = 0,
      minmanapct = 0,
      maxmanapct = 100,
      enabled = true,
      inCombat = false ,
      bands = {
        {
          targetphase = { 'corpse' },
          validtargets = { 'all' },
          min = 0,
          max = 60,
        },
      },
      healResource = "hp",
    },
  },
},
buff = {
  spells = {
    {
      gem = 5,
      spell = "Heroism",
      alias = "",
      enabled = false ,
      bands = {
        {
          targetphase = { 'tank', 'self', 'groupmember', 'pc' },
          validtargets = { 'all' },
        },
      },
    },
  },
},
debuff = {
  spells = {
  },
},
cure = {
  spells = {
    {
      gem = 7,
      spell = "Cure Disease",
      alias = "curedisease",
      curetype = { 'disease' },
      enabled = true,
      bands = {
        {
          targetphase = { 'tank', 'self', 'groupmember' },
          validtargets = { 'all' },
        },
      },
    },
    {
      gem = 7,
      spell = "Cure Poison",
      alias = "curepoision",
      minmana = 0,
      curetype = { 'poison' },
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember' },
          validtargets = { 'all' },
        },
      },
    },
  },
},
script = {
},
}
return StoredConfig