StoredConfig =  {
settings = {
  dodebuff = true,
  doheal = false ,
  dobuff = true,
  docure = false ,
  domelee = true,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = false ,
  dosit = false ,
  doforage = false ,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = false ,
  acleash = 40,
  followdistance = 20,
  zradius = 100,
  campRestDistance = 10,
  maCampAnchor = true,
},
pull = {
  spell = {
    gem = "melee",
    spell = "Brusco's Boastful Bellow",
  },
  radius = 1200,
  zrange = 200,
  pullMinCon = 2,
  pullMaxCon = 7,
  maxLevelDiff = 5,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = false ,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  stayBehind = true,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = false ,
  minmana = 0,
  otoffset = 0,
},
heal = {
  rezoffset = 0,
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
  },
},
buff = {
  spells = {
    {
      gem = 6,
      spell = "Selo's Accelerando",
      alias = "selos",
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'pull' },
          validtargets = { 'all' },
        },
      },
    },
    {
      gem = 5,
      spell = "Verses of Victory",
      alias = "",
      enabled = true,
      inCombat = true,
      inIdle = false ,
      bands = {
        {
          targetphase = { 'self', 'cbt' },
          validtargets = { 'all' },
        },
      },
    },
    {
      gem = 7,
      spell = "Hymn of Restoration",
      alias = false ,
      minmana = 0,
      enabled = true,
      inCombat = true,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'self' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 8,
      spell = "Cassindra's Chorus of Clarity",
      alias = "manasong",
      minmana = 0,
      enabled = true,
      inCombat = true,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'self' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
  },
},
debuff = {
  spells = {
    {
      gem = 3,
      spell = "Song of Twilight",
      alias = "mez",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'notmatar' },
          validtargets = {  },
          min = 0,
          max = 100,
          mintar = 2,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Mezzed' },
    },
    {
      gem = 1,
      spell = "Selo's Consonant Chain",
      alias = "snare",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 0,
          max = 50,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Snared' },
    },
    {
      gem = 2,
      spell = "Tuyen's Chant of Flame",
      alias = "dot",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 0,
          max = 99,
        },
      },
      recast = 0,
      delay = 0,
    },
  },
},
cure = {
  spells = {
  },
},
script = {
},
}
return StoredConfig