StoredConfig =  {
settings = {
  dodebuff = true,
  doheal = true,
  dobuff = true,
  docure = true,
  domelee = false ,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = false ,
  dosit = true,
  doforage = true,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = false ,
  acleash = 50,
  followdistance = 20,
  zradius = 100,
  campRestDistance = 10,
  maCampAnchor = true,
},
pull = {
  spell = {
    gem = "melee",
    spell = "",
  },
  radius = 400,
  zrange = 150,
  pullMinCon = 2,
  pullMaxCon = 5,
  maxLevelDiff = 6,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR', 'DRU', 'SHM' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = false ,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  stayBehind = false ,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = false ,
  minmana = 0,
  otoffset = 0,
},
heal = {
  rezoffset = 0,
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
    {
      gem = 1,
      spell = "Superior Healing",
      alias = "heal",
      enabled = true,
      bands = {
        {
          targetphase = { 'tank', 'self', 'groupmember', 'pc' },
          validtargets = { 'all' },
          min = 0,
          max = 60,
        },
      },
    },
  },
},
buff = {
  spells = {
    {
      gem = 1,
      spell = "Skin like Wood",
      alias = "",
      enabled = false ,
      bands = {
        {
          targetphase = { 'tank', 'groupmember', 'self' },
          validtargets = { 'all' },
        },
      },
    },
    {
      gem = 8,
      spell = "Legacy of Spike",
      alias = "ds",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'tank' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 8,
      spell = "Chloroplast",
      alias = "regen",
      minmana = 0,
      enabled = true,
      inCombat = false ,
      inIdle = true,
      combatOnly = false ,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
  },
},
debuff = {
  spells = {
    {
      gem = 2,
      spell = "Stinging Swarm",
      alias = "swarm",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 20,
          max = 90,
        },
      },
      recast = 0,
      delay = 0,
    },
    {
      gem = 3,
      spell = "Ignite",
      alias = "firenuke",
      minmana = 50,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 10,
          max = 85,
        },
      },
      recast = 0,
      delay = 0,
    },
    {
      gem = 4,
      spell = "Snare",
      alias = "snare",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 10,
          max = 50,
        },
      },
      recast = 0,
      delay = 0,
      dontStack = { 'Snared' },
    },
  },
},
cure = {
  spells = {
    {
      gem = 7,
      spell = "Cure Poison",
      alias = "curepoison",
      minmana = 0,
      curetype = { 'poison' },
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember' },
          validtargets = { 'all' },
        },
      },
    },
    {
      gem = 7,
      spell = "Cure Disease",
      alias = "curedisease",
      minmana = 0,
      curetype = { 'disease' },
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'tank', 'groupmember' },
          validtargets = { 'all' },
        },
      },
    },
  },
},
script = {
},
}
return StoredConfig