StoredConfig =  {
settings = {
  dodebuff = true,
  doheal = false ,
  dobuff = true,
  docure = false ,
  domelee = true,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = false ,
  dosit = false ,
  doforage = false ,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = false ,
  acleash = 40,
  followdistance = 20,
  zradius = 100,
  campRestDistance = 10,
  maCampAnchor = true,
},
pull = {
  spell = {
    gem = "melee",
    spell = "Flame Lick",
    range = 150,
  },
  radius = 700,
  zrange = 200,
  pullMinCon = 2,
  pullMaxCon = 7,
  maxLevelDiff = 6,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = true,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  stayBehind = false ,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = true,
  minmana = 0,
  otoffset = 0,
},
heal = {
  rezoffset = 0,
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
    {
      gem = 1,
      spell = "Greater Healing",
      alias = "heal",
      minmana = 0,
      minmanapct = 0,
      maxmanapct = 100,
      enabled = true,
      bands = {
        {
          targetphase = { 'self', 'groupmember' },
          validtargets = { 'all' },
          min = 0,
          max = 60,
        },
      },
    },
  },
},
buff = {
  spells = {
    {
      gem = 6,
      spell = "Call of Earth",
      alias = "acds",
      minmana = 0,
      enabled = false ,
      bands = {
        {
          targetphase = { 'self', 'groupmember' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 8,
      spell = "Spikecoat",
      alias = "selfiids",
      minmana = 0,
      enabled = false ,
      bands = {
        {
          targetphase = { 'self' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 7,
      spell = "Call of the Predator",
      alias = false ,
      minmana = 0,
      enabled = false ,
      bands = {
        {
          targetphase = { 'self', 'groupbuff' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
    {
      gem = 5,
      spell = "Call of Fire",
      alias = false ,
      minmana = 0,
      enabled = false ,
      bands = {
        {
          targetphase = { 'self' },
          validtargets = { 'all' },
        },
      },
      spellicon = 0,
    },
  },
},
debuff = {
  spells = {
    {
      gem = 3,
      spell = "Drones of Doom",
      alias = "dot",
      minmana = 0,
      enabled = false ,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 30,
          max = 95,
        },
      },
      recast = 3,
      delay = 0,
    },
    {
      gem = 4,
      spell = "Snare",
      alias = "snare",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 10,
          max = 40,
        },
      },
      recast = 3,
      delay = 0,
      dontStack = { 'Snared' },
    },
    {
      gem = "ability",
      spell = "taunt",
      alias = false ,
      minmana = 0,
      enabled = true,
      onlyMT = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 20,
          max = 100,
        },
      },
      recast = 0,
      delay = 0,
      precondition = "return mq.TLO.Me.TargetOfTarget.ID() and mq.TLO.Me.TargetOfTarget.ID() ~= mq.TLO.Me.ID()",
    },
  },
},
cure = {
  spells = {
  },
},
script = {
},
}
return StoredConfig