StoredConfig =  {
settings = {
  dodebuff = true,
  doheal = false ,
  dobuff = true,
  docure = false ,
  domelee = false ,
  doraid = false ,
  dodrag = false ,
  domount = false ,
  mountcast = false ,
  dosit = true,
  doforage = false ,
  sitmana = 90,
  sitendur = 90,
  sitaggro = 60,
  TankName = "automatic",
  TargetFilter = 1,
  petassist = false ,
  acleash = 40,
  followdistance = 20,
  zradius = 100,
  campRestDistance = 10,
  maCampAnchor = true,
},
pull = {
  spell = {
    gem = "melee",
    spell = "",
  },
  radius = 400,
  zrange = 150,
  pullMinCon = 2,
  pullMaxCon = 5,
  maxLevelDiff = 6,
  usePullLevels = false ,
  pullMinLevel = 1,
  pullMaxLevel = 125,
  chainpullhp = 0,
  chainpullcnt = 0,
  mana = 60,
  manaclass = { 'CLR', 'DRU', 'SHM' },
  leash = 500,
  fteLockoutSec = 120,
  backupCandidates = 3,
  addAbortRadius = 50,
  usepriority = false ,
  hunter = false ,
  roam = false ,
},
melee = {
  assistpct = 99,
  stickcmd = "hold uw 7",
  stayBehind = false ,
  behindAggroPct = 90,
  evadePct = 90,
  offtank = false ,
  mtSticky = false ,
  minmana = 0,
  otoffset = 0,
},
heal = {
  rezoffset = 0,
  interruptlevel = 0.8,
  xttargets = 0,
  spells = {
    {
      gem = 8,
      spell = "Harvest",
      alias = "harvest",
      minmana = 0,
      minmanapct = 0,
      maxmanapct = 50,
      enabled = false ,
      bands = {
        {
          targetphase = { 'self' },
          validtargets = { 'all' },
          min = 0,
          max = 100,
        },
      },
      healResource = "mana",
    },
  },
},
buff = {
  spells = {
    {
      gem = 8,
      spell = "Greater Shielding",
      alias = "shield",
      enabled = true,
      bands = {
        {
          targetphase = { 'self' },
          validtargets = { 'all' },
        },
      },
    },
  },
},
debuff = {
  spells = {
    {
      gem = 2,
      spell = "Ice Shock",
      alias = "icenuke",
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 1,
          max = 90,
          aggroMax = 80,
        },
      },
    },
    {
      gem = 1,
      spell = "Conflagration",
      alias = "firenuke",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 1,
          max = 90,
          aggroMax = 80,
        },
      },
      recast = 0,
      delay = 0,
    },
    {
      gem = 4,
      spell = "Draught of Fire",
      alias = "fastfire",
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 20,
          max = 90,
          aggroMax = 80,
        },
      },
      recast = 0,
      delay = 0,
    },
    {
      gem = 3,
      spell = "Rend",
      alias = false ,
      minmana = 0,
      enabled = true,
      bands = {
        {
          targetphase = { 'matar' },
          validtargets = {  },
          min = 1,
          max = 90,
        },
      },
      recast = 0,
      delay = 0,
    },
  },
},
cure = {
  spells = {
  },
},
script = {
},
}
return StoredConfig